definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step:
              name: Lint
              image: node:20
              script:
                - corepack enable
                - corepack prepare pnpm@9.1.1 --activate
                - export PNPM_HOME="/root/.local/share/pnpm"
                - export PATH="$PNPM_HOME:$PATH"
                - pnpm add -g turbo
                - pnpm install
                - cp .env.test .env
                - pnpm lint && pnpm lint:ws
              caches:
                - pnpm
          - step:
              name: Format
              image: node:20
              script:
                - corepack enable
                - corepack prepare pnpm@9.1.1 --activate
                - export PNPM_HOME="/root/.local/share/pnpm"
                - export PATH="$PNPM_HOME:$PATH"
                - pnpm add -g turbo
                - pnpm install
                - cp .env.test .env
                - pnpm format
              caches:
                - pnpm
          - step:
              name: Typecheck
              image: node:20
              script:
                - corepack enable
                - corepack prepare pnpm@9.1.1 --activate
                - export PNPM_HOME="/root/.local/share/pnpm"
                - export PATH="$PNPM_HOME:$PATH"
                - pnpm add -g turbo
                - pnpm install
                - cp .env.test .env
                - pnpm typecheck
              caches:
                - pnpm
