definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

  steps:
    - step: &setup
        name: Setup and install
        script:
          - corepack enable
          - corepack prepare pnpm@9.1.1 --activate
          - export PNPM_HOME="/root/.local/share/pnpm"
          - export PATH="$PNPM_HOME:$PATH"
          - pnpm add -g turbo
          - pnpm install
          - cp .env.example .env

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step:
              name: Lint
              script:
                - *setup
                - pnpm lint && pnpm lint:ws
              caches:
                - pnpm
          - step:
              name: Format
              script:
                - *setup
                - pnpm format
              caches:
                - pnpm
          - step:
              name: Typecheck
              script:
                - *setup
                - pnpm typecheck
              caches:
                - pnpm
